### ISSUE TITLE
update to 1.0.4 failed project

### ISSUE THREAD

**Issue by rshch1** [django-compressor/django-appconf#64] opened 2020-04-01 08:58 UTC
Hi, after your update from 1.0.3 to 1.0.4, my pipeline in project are failing.

```
  File "/home/user/projects/project/venv/local/lib/python2.7/site-packages/appconf/base.py", line 107
    class AppConf(metaclass=AppConfMetaClass):
                           ^
SyntaxError: invalid syntax
```
I had resolve my problem with downgrade version of package, but i think you need to fix it.

Python 2.7
Django 1.11

**Comment by carltongibson** [comment] 2020-04-01 09:42
Duplicate of #59

**Closed as completed by carltongibson** 2020-04-01 09:42 UTC
