### ISSUE TITLE
AppConf ignores @override_settings decorator

### ISSUE THREAD

**Issue by syabro** [django-compressor/django-appconf#29] opened 2015-11-09 11:19 UTC
I've simple conf.py

```python
class RatesConf(AppConf):
    # Disabling this will be useful for testing purposes
    PREMIUM_AUTO_RECALCULATION_ENABLED = True

```

and I'm using 

```
from conf import RatesConf

...
@receiver(quote_rates_data_changed)
def on_quote_rates_data_changed(signal, sender, quote, **kwargs):
    if RatesConf.PREMIUM_AUTO_RECALCULATION_ENABLED:
        ...
````

I set it to `False` for all tests except when I need to test this place. I'm trying to override it with django's `override_settings` decorator:

```python
@override_settings(RATES_PREMIUM_AUTO_RECALCULATION_ENABLED=True)
class RatesSignalsTestCase(TestCase):
    def test_quote_rates_data_changed_signal_run_recalculation(self):
        print RatesConf.PREMIUM_AUTO_RECALCULATION_ENABLED 
```

And I'm getting `False`

**Comment by carltongibson** [comment] 2015-11-09 17:39
OK. At first glance that looks like an issue. Is there any chance you could put it in a minimal test case so I can take a look? (Thanks!)

**Comment by carltongibson** [comment] 2016-03-19 20:33
71c2f93 adds a couple of tests checking the override_settings compat. — they both pass.

On the [discussion on #30](https://github.com/django-compressor/django-appconf/issues/30#issuecomment-195374791) @sergei-maertens pointed out that the problem is likely a loading issue — your app's settings not being imported early enough to be picked up. 

Try adding a (Django) AppConf and importing your (AppConf) AppConf in the `ready` handler there. 

I'm going to close this as "Cannot Reproduce".

I'm very happy to look again if anyone can add a failing test to the AppConf test suite.

**Closed by carltongibson** 2016-03-19 20:33 UTC

**Comment by syabro** [comment] 2016-03-20 09:07
Thanks, will check
