### ISSUE TITLE
Version 1.0.4 is broken for Python 2

### ISSUE THREAD

**Issue by razius** [django-compressor/django-appconf#65] opened 2020-04-01 09:01 UTC
I see version `1.0.4` just removed and broke compatibility with Python 2, this is a bit frustrating as minor and patch versions should never break compatibility.

Please consider releasing `1.0.4` as a major version instead according to the https://semver.org/ guidelines.

**Comment by carltongibson** [comment] 2020-04-01 09:41
Duplicate of #59

**Closed as completed by carltongibson** 2020-04-01 09:41 UTC
