### ISSUE TITLE
Syntax error in Python2 for version 1.0.4

### ISSUE THREAD

**Issue by sshishov** [django-compressor/django-appconf#63] opened 2020-04-01 07:23 UTC
Hello, dear maintainers!

Recent release 1.0.4 broke the compatibility with Python2. How backward-incompatible changes can be `minor` version update, firstly?

Secondly, if these changes are not compatible with python2 due to syntax3-only changes, then the package should not be pushed to PyPy wheel as py2 supported.
You did push it like this: `django_appconf-1.0.4-py2.py3-none-any.whl`. It should be only `py3` then.

We are having the following issue:
```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/user/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/user/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute
    django.setup()
  File "/home/user/venv/local/lib/python2.7/site-packages/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/user/venv/local/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/user/app/venv/local/lib/python2.7/site-packages/django/apps/config.py", line 87, in create
    module = import_module(entry)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/app/tracking/__init__.py", line 1, in <module>
    from receivers import *
  File "/home/user/app/tracking/receivers.py", line 17, in <module>
    from rss.models import RssFeed
  File "/home/user/app/rss/models.py", line 35, in <module>
    from object.models import Category
  File "/home/user/app/object/models/__init__.py", line 24, in <module>
    from django_fsm_log.models import StateLog
  File "/home/user/venv/local/lib/python2.7/site-packages/django_fsm_log/models.py", line 4, in <module>
    from django_fsm_log.conf import settings
  File "/home/user/venv/local/lib/python2.7/site-packages/django_fsm_log/conf.py", line 2, in <module>
    from appconf import AppConf
  File "/home/user/venv/local/lib/python2.7/site-packages/appconf/__init__.py", line 1, in <module>
    from .base import AppConf  # noqa
  File "/home/user/venv/local/lib/python2.7/site-packages/appconf/base.py", line 107
    class AppConf(metaclass=AppConfMetaClass):
```

I understand that Python2 is not supported anymore and it reached end on life. But a lot of companies are still using it, even in production. And changes like these are breaking things which expected to be working. We should not break anything, especially if we can easily avoid it.

**Comment by carltongibson** [comment] 2020-04-01 08:16
Duplicate of #59

**Closed as completed by carltongibson** 2020-04-01 08:16 UTC
