### ISSUE TITLE
Error after upgrading from 1.0.3 to 1.0.4

### ISSUE THREAD

**Issue by alb3rto269** [django-compressor/django-appconf#66] opened 2020-04-01 16:02 UTC
```
Unhandled exception in thread started by <function wrapper at 0x7efff16956e0>
Traceback (most recent call last):
  File "/home/myuser/.virtualenvs/backend/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/home/myuser/.virtualenvs/backend/local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 116, in inner_run
    autoreload.raise_last_exception()
  File "/home/myuser/.virtualenvs/backend/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 251, in raise_last_exception
    six.reraise(*_exception)
  File "/home/myuser/.virtualenvs/backend/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/home/myuser/.virtualenvs/backend/local/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/myuser/.virtualenvs/backend/local/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/myuser/.virtualenvs/backend/local/lib/python2.7/site-packages/django/apps/config.py", line 94, in create
    module = import_module(entry)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/myuser/.virtualenvs/backend/local/lib/python2.7/site-packages/imagekit/__init__.py", line 2, in <module>
    from . import conf
  File "/home/myuser/.virtualenvs/backend/local/lib/python2.7/site-packages/imagekit/conf.py", line 1, in <module>
    from appconf import AppConf
  File "/home/myuser/.virtualenvs/backend/local/lib/python2.7/site-packages/appconf/__init__.py", line 1, in <module>
    from .base import AppConf  # noqa
  File "/home/myuser/.virtualenvs/backend/local/lib/python2.7/site-packages/appconf/base.py", line 107
    class AppConf(metaclass=AppConfMetaClass):
```

I've an old project running in Python 2.7.16 and django==1.11.27. 
If the issue is not occurring with non-deprecated versions of python/django feel free to close this.

**Comment by carltongibson** [comment] 2020-04-01 18:51
Duplicate of #59. 

Yes, please pin to 1.0.3.

**Closed as completed by carltongibson** 2020-04-01 18:51 UTC
