### ISSUE TITLE
Missing settings in test classmethod setUpTestData()

### ISSUE THREAD

**Issue by jedie** [django-compressor/django-appconf#41] opened 2018-02-28 11:42 UTC
Python 2.7

Django==1.8.18
django-appconf==1.0.2
pytest==3.4.1
pytest-cov==2.5.1
pytest-django==3.1.2

AppConf settings will be not available in test classmethod **setUpTestData()** or **setUpClass()**
Maybe it depend on django-pytest and his test runner ?!?

I tried to add a **apps.py** similar to: https://github.com/julen/django-statici18n/commit/7638920e7be8247857fad36b422d977bcac3cf60
But this doesn't help.

I tried to import the app config class in **setUpTestData()** or **setUpClass()** but this doesn't the settings, too.

The only work-a-round for me was to add the settings manually in settings.py :(

**Comment by carltongibson** [comment] 2018-02-28 14:09
Hi @jedie. 

This seems to be the same issue as #30, no? 

If it's different, can you provide an example of how to reproduce this?

**Comment by carltongibson** [comment] 2018-02-28 15:30
I'm going to close this as-is. I'm happy to re-open if you can come up with a concrete reproduce.

Once thought: issues seems to be not importing early enough. You're using py.test, so how about in `contest.py`? 

Short of that working I need SOMETHING to go on...

**Closed as completed by carltongibson** 2018-02-28 15:30 UTC
